### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by ac-amygdala** [Vadim-SKUp/SkillUp-lessons#2]
Большая просьба - выдерживать структурные отступы в верстке.

Буквально пару правил:
- Открывающий и закрывающий тег одного элемента - с одинаковым отступом
- Вложенный контент в тег - с отступом на один шаг больше родителя

Хорошее форматирование помогает проще читать структуру верстки
Как вариант - можно использовать инструменты типа http://beautifytools.com/html-beautifier.php

**Comment by ac-amygdala** [comment]
То же самое можно плагинами настроить в принципе
Но лучше всего - стараться самому выдерживать стиль

**Comment by Vadim-SKUp** [comment]
Понял. Я в некоторых случаях стараюсь выдерживать это, а иногда забываю и не обращаю внимания.
