### ISSUE TITLE
Атрибуты и единицы измерений

### ISSUE THREAD

**Issue by ac-amygdala** [Vadim-SKUp/SkillUp-lessons#3]
https://github.com/Vadim-SKUp/SkillUp-lessons/blob/2ceaa9db0c3b29d05e5b037b0c67c3df817ff9c0/homework_1/index.html#L55

Атрибуты не оперируют единицами измерения. Берется только числовая составляющая из значения. Для разных атрибутов потом подставляется соответствующая единица измерения.

А в `css` единицы обязательны.

`<img src="..." width="500" />`
`<img src="..." width="500px" />`
`<img src="..." width="500em" />`

дадут в результате одни и те же размеры

Поэтому в стандарте закрепили использование значений атрибутов исключительно без единиц измерения.

**Comment by Vadim-SKUp** [comment]
понял
