### ISSUE TITLE
Структура папок

### ISSUE THREAD

**Issue by ac-amygdala** [Vadim-SKUp/SkillUp-lessons#4]
Желательно картинки складывать в отдельную папку рядом
Css - тоже в отдельную в дальнейшем

Когда много файлов разного типа на одном уровне - бывает сложно ориентироваться
Это просто пожелание - просто чем раньше следовать определенным практикам - тем проще потом соблюдать чистоту кода и проекта

**Comment by Vadim-SKUp** [comment]
Ну, тут просто маленькая страница была и только две картинки, поэтому я не структурировал по папкам. 
Если бы проект был больше, я бы конечно сортировал по папкам.
